spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
name: zhangsan233
  rabbitmq:
    host: 192.168.154.130
    username: guest
    password: guest
    port: 5672
 
