spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
  rabbitmq:
    host: 192.168.154.130
    port: 5672
    username: guest
    password: guest
name: zhangsan888
 
