server:
  port: 9999
spring:
  application:
    name: users
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
#products:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeOut: 5000 #连接时间
        readTimeOut: 5000 #最大等待时长
  hystrix:
    enabled: true
logging:
  level:
    com:
      imooc:
        client: debug
